// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BuildTimeLogger
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidBuildTimeLoggerPackageString = "9a35dbc8-ada9-46fb-b3fd-c224bd07427b";
        public static Guid guidBuildTimeLoggerPackage = new Guid(guidBuildTimeLoggerPackageString);

        public const string guidBuildTimeLoggerPackageCmdSetString = "a9634269-f80d-44b8-a284-cf623c10fba0";
        public static Guid guidBuildTimeLoggerPackageCmdSet = new Guid(guidBuildTimeLoggerPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidTestConnectionToolWindowCommand = 0x0101;
    }
}